### ISSUE TITLE
Increase privacy awarness

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#119] opened 2021-03-14 18:20 UTC
![image](https://user-images.githubusercontent.com/8873352/111079404-cb6f8400-84f1-11eb-908f-89d6005bdd97.png)
Could you design something like that which emphasize on privacy by displaying the user its address and giving privacy advice.

**Comment by jragosa** [comment] 2021-03-15 08:41
Duplicate of #114, You can close one or the other.

**Comment by pliniobraga** [comment] 2021-03-15 19:05
Updated it on the design according to the suggestions from issues #119 and #114:

![update-message](https://user-images.githubusercontent.com/15757255/111207310-3bd8dc80-85a8-11eb-864b-dcb85bb7e395.png)

**Comment by jragosa** [comment] 2021-03-16 07:59
Love it 👍

**Comment by clesaege** [comment] 2021-03-21 20:38
The page has a lot of important information, the current implementation is placing too much emphasis on the privacy part. Any emphasis on information is diluting the emphasis on other information.
I suggest to go with the design I proposed which make people aware of privacy without scaring potential users or diluting their attention.
As a general rule, use of CAPS should be avoided and warning signs be reserved for when the user is doing an action which is most likely dangerous.

**Comment by pliniobraga** [comment] 2021-03-22 00:01
Updated it according to the initial proposal:
![update](https://user-images.githubusercontent.com/15757255/111925597-515a7480-8a88-11eb-9e6f-6d35fe362a72.png)

**Closed** 2021-04-15 17:44 UTC
Labels: priority: medium, status: in progress, type: enhancement :sparkles:
