### ISSUE TITLE
Small error when displaying timestamp:

### ISSUE THREAD

**Issue by matiu** [Proof-Of-Humanity/proof-of-humanity-web#116] opened 2021-03-14 14:51 UTC
**Describe the Bug**
This was taken from a profile.
<img width="205" alt="Screen Shot 2021-03-14 at 11 49 01 AM" src="https://user-images.githubusercontent.com/98844/111072927-71ec6280-84bb-11eb-9c22-e50e34fec350.png">

**To Reproduce**
If you can't reproduce it, PM at twitter @ematiu to ge the URL, I prefer not to post it here

**Expected Behavior**
Accepted / renewal should be null.
**Screenshots**

**Device and Browser Information**

**Comment by jragosa** [comment] 2021-03-14 15:08
Duplicate of https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/112

**Closed** 2021-03-17 14:09 UTC
Labels: duplicate :two:
