### ISSUE TITLE
Extremely high gas (.7 or .8 eth) required for a challenge. (But gas is at 56 gwei.)

### ISSUE THREAD

**Issue by dogweather** [Proof-Of-Humanity/proof-of-humanity-web#319] opened 2021-05-18 04:10 UTC
**Describe the Bug**

I'm trying to start a challenge, but Metamask states that .7 or .8 eth (USD 2,300+) for gas is required.

**Expected Behavior**

Gas should be far less, under $100 at the moment. (Based on txns seen on etherscan which were done a couple of hours ago.)

**Screenshots**

<img width="472" alt="High gas fees" src="https://user-images.githubusercontent.com/150670/118588913-96371a80-b75c-11eb-8507-d93cd2c4f8a3.png">

**Device and Browser Information**

Chrome browser + Metamask

**Comment by dogweather** [comment] 2021-05-18 05:51
I found that I only get this extreme gas fee when using Metamask.

**Comment by mmiguerodriguez** [comment] 2021-05-18 13:02
You probably don't have enough funds. Possible duplicate of #256 .

**Comment by mtsalenc** [comment] 2021-05-18 19:33
Another reason metamask gives incorrect predictions is because the transaction would revert. Did someone else challenge it before you?

**Comment by dogweather** [comment] 2021-05-21 00:33
Nope - I was able to challenge it just fine using another wallet.

**Comment by mtsalenc** [comment] 2021-05-26 19:15
It seems to not be a problem anymore. If it happens again please reopen, join https://t.me/pohDebug and DM me the affected profile.

**Closed by mtsalenc** 2021-05-26 19:15 UTC

**Comment by dogweather** [comment] 2021-05-27 06:48
My wife just had the same problem: On her Mac this time, using Brave with Metamask:

![metamask high fees](https://user-images.githubusercontent.com/150670/119778778-26740e80-be85-11eb-8b57-72d55588e4c2.jpeg)

**Comment by dogweather** [comment] 2021-05-27 09:20
I've discovered this is a known Metamask issue when the wallet doesn't have enough funds for a transaction: https://github.com/MetaMask/metamask-extension/issues/10276
