### ISSUE TITLE
Submit profile doesn't work

### ISSUE THREAD

**Issue by erickobrinsky** [Proof-Of-Humanity/proof-of-humanity-web#217] opened 2021-04-15 14:04 UTC
I uploaded the profile, I transferred the eth funds from Metamask,  but the submit keeps loading and does not allow me to move forward.

My Metamask ID is: 0xcf2Da623F0400a91b4A91C6c14B52ea41fa6D54A

<img width="819" alt="Capture" src="https://user-images.githubusercontent.com/78773449/114881861-c2682000-9dd9-11eb-9f86-57e77568bf92.PNG">

Google Chrome, Notebook

**Comment by mtsalenc** [comment] 2021-04-15 17:42
Did you sign the transaction on metamask?

**Comment by erickobrinsky** [comment] 2021-04-15 18:03
Yes, I signed the transaction on Metamask.

**Comment by mtsalenc** [comment] 2021-04-15 18:18
Good, I can see your transaction was included in a block so everything went fine. 

That being said, there is some instability in the network related to a recent hardfork which is causing the UI to be outdated. No action is required from you besides waiting finding someone already accepted to vouch for you.

Once the network stabilizes you will be able to see your profile. 

I'll leave this open until we confirm.

**Comment by erickobrinsky** [comment] 2021-04-15 18:37
Great, thanks @mtsalenc !

**Comment by jmartinez042** [comment] 2021-04-15 19:07
Hi, I have the same problem, mi metamask ID is:
0xD0DB216E951c065F5dB2269C6EaFB69A8B61Ee12

**Comment by mtsalenc** [comment] 2021-04-16 16:09
jmartinez, everything is fine with your submission too: https://app.proofofhumanity.id/profile/0xD0DB216E951c065F5dB2269C6EaFB69A8B61Ee12

**Comment by mtsalenc** [comment] 2021-04-16 16:09
Closing this as it was caused by a temporary outage on The Graph's hosted service, not a UI bug.

**Closed by mtsalenc** 2021-04-16 16:09 UTC
