### ISSUE TITLE
Add a warning message at the top of the submit page

### ISSUE THREAD

**Issue by jragosa** [Proof-Of-Humanity/proof-of-humanity-web#114] opened 2021-03-14 14:15 UTC
Some users don't know that they are about to immutably link their Ethereum address to their identity. 

Add this message ina visible way at the top of the submit page.

`PRIVACY WARNING: The Ethereum address you are using to submit your profile will be publicly linked to your identity. If you don't want your wallet holdings and transaction history to be linked to your identity, we recommend using a new Ethereum address."

![image](https://user-images.githubusercontent.com/34345327/111071692-9c4c1900-84d7-11eb-8fac-6aadb82608f0.png)

**Comment by mtsalenc** [comment] 2021-03-15 14:11
Duplicate of https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/119

**Closed by mtsalenc** 2021-03-15 14:11 UTC
Labels: enhancement
