### ISSUE TITLE
When vouched by someone whose vouch is already used explain it

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#121] opened 2021-03-14 18:34 UTC
![image](https://user-images.githubusercontent.com/8873352/111079885-f3f87d80-84f3-11eb-90b0-a577dede8c20.png)

**Comment by jragosa** [comment] 2021-03-15 08:40
Can merge this one with https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/114

**Comment by pliniobraga** [comment] 2021-03-15 18:03
What do you think of this solution? Basically, we display the (Vouched by) and (Vouched for) in all profiles, then in order, we display the Vouchers in the queue with lower opacity and the message: "In the queue".

![Update Suggestion](https://user-images.githubusercontent.com/15757255/111199607-9883c980-859f-11eb-88f6-033a0296c2cf.png)

**Comment by jragosa** [comment] 2021-03-16 08:00
Love it 👍

**Comment by jragosa** [comment] 2021-03-17 14:11
Duplicate of #115

**Closed by jragosa** 2021-03-17 14:11 UTC
Labels: duplicate :two:
