### ISSUE TITLE
Video doesn't show for this profile (sound is OK)

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#134] opened 2021-03-16 21:43 UTC
https://app.proofofhumanity.id/profile/0x2D5b5c943D04EC56EDCA996cc7963Ca50EB57Ba6?network=mainnet

**Comment by jragosa** [comment] 2021-03-17 14:17
If the dev assigned is unable to find the root cause, we need to contact the guy through evidence and ask him to remove and resubmit.

**Comment by rommeldbx** [comment] 2021-03-20 16:46
Same problem to my profile video
https://app.proofofhumanity.id/profile/0x6CF07f01c3DEBeFfc4316E3F9aA7e13E50CE70AD?network=mainnet

**Comment by Germoe** [comment] 2021-03-28 21:06
Same problem for this profile https://app.proofofhumanity.id/profile/0xf11Dd9a593F2013c0F981bE7fAA1fD560e035a8F?network=mainnet

Video looks fine if downloaded.

**Comment by ferittuncer** [comment] 2021-03-29 11:36
It's because MPEG-4 is supported by neither Chrome nor Firefox.

Test here: http://demo.nimius.net/video_test/

**Comment by ferittuncer** [comment] 2021-03-29 11:49
When a video with an unsupported codec is uploaded, the video does not play in the submission form. Users should check for this. I'm going to add a warning as an extra.

**Comment by rommeldbx** [comment] 2021-03-29 11:55
Thanks a lot!!!!!

> When a video with an unsupported codec is uploaded, the video does not play in the submission form. Users should check for this. I'm going to add a warning as an extra.

**Comment by ferittuncer** [comment] 2021-03-29 12:02
Note that, codec supports are not related to this application, it is about the web browser the user is using.

**Comment by clesaege** [comment] 2021-03-29 15:55
Well we should probably modify the rules to forbid .avi videos in the future.

**Comment by Germoe** [comment] 2021-04-04 20:03
How would I go about correcting this issue now with the current profile already submitted?

**Comment by mtsalenc** [comment] 2021-04-05 15:55
> How would I go about correcting this issue now with the current profile already submitted?

If your profile has no vouches you should click the "withdraw" submission button to get your deposit back, and resubmit.

**Comment by rommeldbx** [comment] 2021-04-05 16:05
Could someone vouchme pls?

**Comment by rommeldbx** [comment] 2021-04-06 11:11
Could someone vouch me pls? If not I ve to make all the process again. THKS!
https://app.proofofhumanity.id/profile/0x6CF07f01c3DEBeFfc4316E3F9aA7e13E50CE70AD?network=mainnet

**Comment by mtsalenc** [comment] 2021-06-01 17:01
Closing this since it is not something we can control (besides restricting file types in the UI, which is done).

**Closed by mtsalenc** 2021-06-01 17:01 UTC
Labels: priority: medium, status: on hold, type: bug :bug:
