### ISSUE TITLE
complete the deposit yesterday and today the deposit is 85% complete.

### ISSUE THREAD

**Issue by Gabrieltropea** [Proof-Of-Humanity/proof-of-humanity-web#264] opened 2021-04-30 14:17 UTC
When I uploaded the video for the initial registration, I had to make a deposit of ETH, at that time I did not have enough balance in my virtual wallet, so I was left with approximately 45% of the total deposit. After 3 weeks I realized that if I did not deposit 100%, I would not be registered, so yesterday, 04/28 I proceeded with the deposit I was missing for a total of 0.087 ETH to complete the deposit. I made that transaction, which is registered in my virtual wallet, and indeed the 100% deposit appeared in my profile on the page. Today, 04/30, I logged into my profile to see if the registration had advanced and I found that in the part where the deposit appears it says 85%, which is wrong and I don't understand why it changed. Not only am I not going to be registered, but also 15% of my deposit has disappeared. Please, I would like to know what happened and if you can verify it to fix it. Thank you very much and Regards.

**Comment by mtsalenc** [comment] 2021-04-30 19:45
This was a UI bug solved by https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/266.
Duplicate of https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/263
Please reopen if you still have an issues.

**Closed by mtsalenc** 2021-04-30 19:45 UTC
