### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by ChrisRanas** [Proof-Of-Humanity/proof-of-humanity-web#203] opened 2021-04-10 08:57 UTC
Hi,

After I registered my sister the submit button is only loading and the transaction fee is already deducted on her eth account wallet. As of now after 3 hours her account still not on the profile page. Kindly please help to fix this.

thank you...

**Comment by vanagasl** [comment] 2021-04-10 11:42
Hi, Same situation here! I completed the submission information some minutes ago. When approving the transaction with Metamask, I was returned to an empty submission page, with the "Submit" button in a loading state and both the deposit and transaction fee have been deducted.   Is there a way to verify that the submission is correct?

**Comment by Matasinver** [comment] 2021-04-10 14:36
Hello. The same issue here. I´ve submited the profile and deposit was retained, but I can´t see the profile. Please, can help me?

**Comment by martymulligan** [comment] 2021-04-10 23:36
This same thing is happening to me.  I think the issue is caused by a lag in the indexing of the PoH subgraph. When I check the network console, I see the following error message in the response to https://api.thegraph.com/subgraphs/name/kleros/proof-of-humanity-mainnet

```
{"errors":[{"message":"Failed to decode `block.number` value: `subgraph QmZn3ihLok9zMJCQT5JqpS1EPzTzRnLckLCuwv6tJzrymm has only indexed up to block number 12208990 and data for block number 12215040 is therefore not yet available`"}]}
```

So my submission appears to have been received but hasn't been indexed yet, so the UI fails under the hood.  Maybe the UI could handle this error more gracefully with a message indicating to the user that their submission has been received and will appear in the UI when the block their transaction was added to is indexed.

**Comment by mtsalenc** [comment] 2021-04-12 19:15
Yes there was an outage in PoH's subgraph this Saturday. Are any of you still experiencing this?

**Comment by martymulligan** [comment] 2021-04-14 13:32
@mtsalenc for my part, it was resolved within a day or so

**Comment by mtsalenc** [comment] 2021-06-01 17:05
Closing this as it was a temporary outage.

**Closed by mtsalenc** 2021-06-01 17:05 UTC
