### ISSUE TITLE
I can't see my own profile neither other people at Vouching phase

### ISSUE THREAD

**Issue by diegoflores111** [Proof-Of-Humanity/proof-of-humanity-web#269] opened 2021-04-30 19:59 UTC
I submitted my profile for getting vouched, and I am noticing I can't see my profile neither do other people, and actually I checked other people and I can't see some profiles. it says "An unexpected error has occurred."

**Comment by DaniNz** [comment] 2021-04-30 20:55
I have the same error on my [profile](https://app.proofofhumanity.id/profile/0x72DffE59467384d495DC424b3cc72c7bE7950b11)

![image](https://user-images.githubusercontent.com/16692007/116752974-bd5fbf00-a9dc-11eb-9bef-f102756526bb.png)

**Comment by Lucas-bck** [comment] 2021-04-30 21:24
Same issue on my profile, [LINK](https://app.proofofhumanity.id/profile/0x410c92BCE3CBE850499F4373029fF19EFFC11748)

**Comment by jfdominguez1** [comment] 2021-04-30 21:33
Same issue here

[https://app.proofofhumanity.id/profile/0x18fcaaf8b48b73a039dae997268b4045199f9ba8](url)

**Comment by mateoneira** [comment] 2021-04-30 21:55
I'm having similar issues when checking other peoples profiles. Error seems to be only on some profiles.

**Comment by mtsalenc** [comment] 2021-04-30 22:42
Duplicate of https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/268
Fixed by https://github.com/Proof-Of-Humanity/proof-of-humanity-web/pull/270

**Closed by mtsalenc** 2021-04-30 22:42 UTC
